BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `t_usr_ingredient` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_ingridient`	INTEGER,
	`user`	TEXT,
	`amount`	REAL
);
CREATE TABLE IF NOT EXISTS `T_Ingredients_DAT` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`unit`	TEXT
);
CREATE TABLE IF NOT EXISTS `t_meal_ingredient` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`id_meal`	INTEGER,
	`id_ingredient`	INTEGER,
	`amount`	INTEGER
);
CREATE TABLE IF NOT EXISTS `T_MEAL_DAT` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`name`	TEXT,
	`url`	TEXT,
	`rating`	REAL
);
COMMIT;
